logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %highlight(%5p ) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

#server:
#  servlet:
#    context-path: /api

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sampledb
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
  webflux:
    format:
      date-time:  yyyy-MM-dd HH:mm:ss
  jackson:
    serialization:
      fail-on-empty-beans: false
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false