version: "2.1"
services:
  app:
    image: las-cuentas-claras
    container_name: las-cuentas-claras
    ports:
      - 8080:8080 
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo-las-cuentas-claras
    depends_on: 
      - db
  db:
    image: mongo
    container_name: mongo-las-cuentas-claras
    volumes:
      - ./database:/data
    ports:
      - "27017:27017"